// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Stores = sequelize.define('stores', {
    name: {
      type: DataTypes.STRING,
    },
    sunday: {
      type: DataTypes.BOOLEAN,
      defaultValue: true,
    },
    monday: {
      type: DataTypes.BOOLEAN,
      defaultValue: true,
    },
    tuesday: {
      type: DataTypes.BOOLEAN,
      defaultValue: true,
    },
    wednesday: {
      type: DataTypes.BOOLEAN,
      defaultValue: true,
    },
    thursday: {
      type: DataTypes.BOOLEAN,
      defaultValue: true,
    },
    friday: {
      type: DataTypes.BOOLEAN,
      defaultValue: true,
    },
    saturday: {
      type: DataTypes.BOOLEAN,
      defaultValue: true,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    addressableType: {
      type: DataTypes.STRING,
    },
    addressableId: {
      type: DataTypes.BIGINT,
    },
    nextDayHour: {
      type: DataTypes.DOUBLE,
      defaultValue: 0.0,
    },
    dayForOrder: {
      type: DataTypes.DOUBLE,
      defaultValue: 0.0,
    },
    flags: {
      type: DataTypes.STRING,
      defaultValue: "",
    },
  }, {
    tableName: 'stores',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Stores.associate = (models) => {
    Stores.belongsTo(models.restaurants, {
      foreignKey: {
        name: 'restaurantIdKey',
        field: 'restaurant_id',
      },
      as: 'restaurant',
    });
  };

  return Stores;
};
